server:
  port: 8761
spring:
  application:
    name: discovery-service
eureka:
  server:
    wait-time-in-ms-when-sync-empty: 0
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
  username: ${EUREKA_USERNAME:eureka}
  password: ${EUREKA_PASSWORD:password}
